[control_plane]
192.168.68.71 node_name=node1 node_label=storage

[nodes]
192.168.68.72 node_name=node2 node_label=jellyfin
#192.168.68.73 node_name=node3

[usb_storage]
192.168.68.71

[cluster:children]
control_plane
nodes

[cluster:vars]
ansible_user=steff
