---
- name: Argocd - Git checkout HEAD of repo containing application sets
  ansible.builtin.git:
    repo: 'https://github.com/steffkelsey/homelab-live.git'
    dest: ~/github/homelab-live
    single_branch: true

- name: ArgoCD - Make sure the argocd namespace exists
  kubernetes.core.k8s:
    api_version: v1
    kind: Namespace
    name: argocd
    state: present
    kubeconfig: /etc/rancher/k3s/k3s.yaml
  vars:
    ansible_python_interpreter: "{{ venv_dir }}/bin/python"

- name: Argocd - Upgrade or install ArgoCD via Helm chart into argocd namespace
  kubernetes.core.helm:
    name: argocd
    chart_ref: oci://ghcr.io/argoproj/argo-helm/argo-cd
    chart_version: "{{ argocd_chart_version }}"
    release_namespace: argocd
    kubeconfig: /etc/rancher/k3s/k3s.yaml
    state: present # equiv to helm upgrade --install

- name: Argocd - Create ApplicationSets in k8s from file
  kubernetes.core.k8s:
    state: present
    src: ~/github/homelab-live/application-sets/production.yaml
    kubeconfig: /etc/rancher/k3s/k3s.yaml
  vars:
    ansible_python_interpreter: "{{ venv_dir }}/bin/python"
