---
- name: kubernetes-client - Install kubernetes client python package
  ansible.builtin.pip:
    name: kubernetes
    virtualenv: "{{ venv_dir }}"
    virtualenv_command: "{{ ansible_facts['python']['executable'] }} -m venv"
