---
- name: namedotcom-secret - Maybe fail if missing name.com api env variables on local
  delegate_to: localhost
  ansible.builtin.fail:
    msg: Env vars NAMEDOTCOM_USERNAME and NAMEDOTCOM_TOKEN must be set to proceed with creating kubernetes secret
  vars:
    has_username: "{{ lookup('ansible.builtin.env', 'NAMEDOTCOM_USERNAME') | length > 0 }}"
    has_token: "{{ lookup('ansible.builtin.env', 'NAMEDOTCOM_TOKEN') | length > 0 }}"
  when: 
    - (not has_username or not has_token)

- name: namedotcom-secret - Maybe create name.com API secret
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        namespace: kube-system
        name: namedotcom-api
      type: Opaque
      stringData:
        username: "{{ lookup('ansible.builtin.env', 'NAMEDOTCOM_USERNAME') }}"
        token: "{{ lookup('ansible.builtin.env', 'NAMEDOTCOM_TOKEN') }}"
    kubeconfig: /etc/rancher/k3s/k3s.yaml
  vars:
    ansible_python_interpreter: "{{ venv_dir }}/bin/python"
